name: Konwersja Modelu GLiNER do TFLite

on:
  workflow_dispatch:

jobs:
  convert:
    name: Generowanie Struktur AI dla Androida
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Uruchomienie naszego w 100% odpornego na błędy sieciowe skryptu
    - name: Run Model and Tokenizer Local Generation
      run: python convert_gliner.py

    # Wypchnięcie gotowej paczki ze słownikiem do sekcji Artifacts
    - name: Upload Finished Model Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Gliner-2.5-Android-Models
        path: |
          gliner_output/gliner_2.5_fp16.tflite
          gliner_output/tokenizer.json
        retention-days: 3
